### ISSUE TITLE
Standalone M1 Mac application - nothing happens when trying to transcribe timeline

### ISSUE THREAD

**Issue by oollyy** [octimot/StoryToolkitAI#83] opened 2023-04-02 16:22 UTC
Hey there,

I've downloaded v0.17.16.1, running on Mac OS Ventura 13.2.1 (22D68) on an M1 Max. 
Added to Applications folder and allowed the app to run in Security settings.
I open Resolve 18.1.4 Build 9. 
I open my timeline (in this case, it's a 25 second clip I wanted to test the software on). 
I open StoryToolkitAI and it shows me the correct menu buttons.
I hit 'Transcribe Timeline' and nothing happens. I hit Translate Timeline to English, and nothing happens.
I open and close both applications, the same issue occurs. I know StoryToolkit can sense Resolve is open, because it adjusts menu items when I open it first instead of Resolve.

Am I missing something here or is this just a bug on Mac?

**Comment by octimot** [comment] 2023-04-02 19:41
I haven't seen this happening, once Resolve is connected. 

Could you please attach an app.log? 

Also, stupid question, but I have to ask... do you have a timeline open in Resolve? (It's not enough to just select it in the Media Bin)

Cheers

**Comment by octimot** [comment] 2023-04-03 06:08
BTW, you can find the app.log by clicking on File -> Configuration Directory

**Comment by Mkhozi** [comment] 2023-04-04 05:57
Issue is related to https://github.com/octimot/StoryToolkitAI/issues/82
The Davinci related buttons are failing due to missing project.json
The root cause is a misplaced "or" statement in app.py
For more details, please see
https://github.com/octimot/StoryToolkitAI/issues/82

**Comment by octimot** [comment] 2023-04-04 18:59
@oollyy closing this issue - please see #82

**Closed by octimot** 2023-04-04 18:59 UTC
Labels: bug

**Comment by octimot** [comment] 2023-04-05 06:33
@oollyy 
I just uploaded the fixed standalone release [StoryToolkitAI 0.17.16.2 for Mac M1, M2 etc.](https://github.com/octimot/StoryToolkitAI/releases/download/v0.17.16/StoryToolkitAI.0.17.16.2.arm64.app.zip)

Please try it and let us know if it works on your end.
