### ISSUE TITLE
Resolve timeline not available

### ISSUE THREAD

**Issue by trulslie** [octimot/StoryToolkitAI#46] opened 2023-01-15 10:41 UTC
Any suggestions here, as when hitting "Translate Audio" 
in StoryToolkitAS v0.17.6.2 with Resolve 18, and Mac Monterey 12.5.1 ? 
I get "A Resolve Timeline is not available ..."

**Comment by octimot** [comment] 2023-01-18 17:58
Hey there!
Silly question, but is the timeline that you're trying to translate open?

**Comment by yorjaggy** [comment] 2023-01-18 22:20
For me, DaVinci was not available because I'm using the free version 😢

**Comment by isazaly** [comment] 2023-01-25 13:55
"A Resolve Timeline is not available ..." also pops up for me. 
It works on my Intel Mac, but not on my M1 Mac.

**Comment by octimot** [comment] 2023-02-01 10:14
If the timeline that you're trying to translate is open in the timeline pane, this shouldn't happen.

Could you drop your log file? Maybe we can figure it out... 

On MacOS, the logs are in `/Users/[YOUR-USERNAME]/StoryToolkitAI/app.log`

**Comment by isazaly** [comment] 2023-02-01 13:52
here you go.


*Isazaly Mohamed Isa @ ZaleePost-Producer*
Kino-i Pictures Sdn Bhd

[image: website] <https://kino-i.com/>


email:* ***@***.*** ***@***.***>*
mobile/whatsapp: *+6012.287.5363*
office +603.4021.2368

<https://www.facebook.com/isazaly/>  <https://www.instagram.com/isazaly/>
<https://www.linkedin.com/in/isazaly/>
<https://www.youtube.com/c/KinoiKualaLumpur>

_______________________________________________________

DISCLAIMER: This message contains confidential information and is intended
only for the individual named. If you are not the named addressee you
should not disseminate, distribute or copy this e-mail. Please notify the
sender immediately by e-mail if you have received this e-mail by mistake
and delete this e-mail from your system. E-mail transmission cannot be
guaranteed to be secure or error-free as information could be intercepted,
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses.
The sender therefore does not accept liability for any errors or omissions
in the contents of this message, which arise as a result of e-mail
transmission.

**Comment by cindrivani** [comment] 2023-02-02 14:51
> If the timeline that you're trying to translate is open in the timeline pane, this shouldn't happen.
> 
> Could you drop your log file? Maybe we can figure it out...
> 
> On MacOS, the logs are in `/Users/[YOUR-USERNAME]/StoryToolkitAI/app.log`

Hello octimot, I havn't StoryToolkitAI/app.log in the folder you've described, neither in my whole drive, according to spotlight

**Comment by octimot** [comment] 2023-02-08 10:06
@isazaly The log file wasn't attached to your message. I think it's best if you use Github directly.

@cindrivani Sorry for the dumb question, but did you replace [YOUR-USERNAME] with your actual username?

To everyone who is seeing this window:
Please read [the instructions](https://github.com/octimot/StoryToolkitAI) thoroughly on the Github page together with the issues that have been opened so far. If this still doesn't work, we will need a log file to understand exactly what is happening on your system. 

Also, you are seeing this warning window because Resolve is not connected to StorytoolkitAI. The warning window itself is expected behaviour if the connection is not active. 

This could happen due to a number of reasons, including not using the Studio version of Resolve, not having Resolve scripting properly configured, having too many python installations on your machine (especially on Windows) etc.  Therefore, I'm going to close this issue and consider it a Resolve API connection problem - there are other open and closed issues regarding that, please message on those issues that fit your situation best and we will try to solve it at best as we can.

Thanks!

**Closed by octimot** 2023-02-08 10:06 UTC
