### ISSUE TITLE
Only Showing The Last Line In The Transcription

### ISSUE THREAD

**Issue by gmrmole** [octimot/StoryToolkitAI#110] opened 2023-06-16 19:05 UTC
**Describe the bug**
When I run transcribe from audio, after it is done processing the SRT file only has the last line and not the full script.
However;I can see the script being generated in the Terminal window with no errors.

<img width="1146" alt="Screenshot 2023-06-16 at 3 03 17 PM" src="https://github.com/octimot/StoryToolkitAI/assets/136848457/08e326aa-2c0b-4422-9274-fc3e4b65fcc9">

**System (please complete the following information):**
 - OS: MacOS 13
 - Python versions installed on machine: 3.10
 - StoryToolkitAI Version 0.19

**Comment by octimot** [comment] 2023-06-16 19:46
Can you try to do a `git pull`? I pushed a few fixes a few hours ago which address issues like this.

Cheers!

**Comment by gmrmole** [comment] 2023-06-16 20:27
Yes, I did- this bug was from the latest fixes.

**Comment by octimot** [comment] 2023-06-17 03:25
That's weird. We're unable to reproduce this error here.

If you check the app.log, do you see any errors or warnings in the session when this happened? Or did you notice anything unusual, like an exception or an error, while it was transcribing?

Would you mind uploading the log and the transcription.json file here?

Cheers

**Comment by octimot** [comment] 2023-06-17 12:35
Nevermind... we found the source and working on a patch!

**Comment by octimot** [comment] 2023-06-17 13:25
I just pushed the fix. Feel free to re-open this if it doesn't work on your side.

Cheers!

**Closed by octimot** 2023-06-17 13:25 UTC
Labels: bug
