### ISSUE TITLE
Windows Standalone 0.17.16 doesn't start (python_check error)

### ISSUE THREAD

**Issue by hiddenpeanuts** [octimot/StoryToolkitAI#78] opened 2023-03-28 11:58 UTC
on Windows. when I start it up, I get this output:

INFO: Running StoryToolkitAI version 0.17.16 (standalone)
INFO: Using cpu for Torch / Whisper.
Traceback (most recent call last):
  File "app.py", line 12042, in <module>
  File "app.py", line 7338, in __init__
  File "mots_resolve.py", line 64, in __init__
  File "mots_resolve.py", line 85, in python_check
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[37088] Failed to execute script 'app' due to unhandled exception!

I'm still able to run the previous non-standalone Windows version.

**Comment by octimot** [comment] 2023-03-28 12:44
It looks like an incomplete installation or a permission problem. Did you by any chance install this in the Program Files folder?

**Comment by octimot** [comment] 2023-03-28 15:56
Did you try to uninstall and then run the installer again? If the installation is incomplete, simply moving it would not help.

Cheers!

**Comment by hiddenpeanuts** [comment] 2023-03-28 16:21
I just tried a full uninstall/reinstall in the new location, but still see the same error:

INFO: Running StoryToolkitAI version 0.17.16 (standalone)
INFO: Using cpu for Torch / Whisper.
Traceback (most recent call last):
  File "app.py", line 12042, in <module>
  File "app.py", line 7338, in __init__
  File "mots_resolve.py", line 64, in __init__
  File "mots_resolve.py", line 85, in python_check
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[23508] Failed to execute script 'app' due to unhandled exception!

**Comment by octimot** [comment] 2023-03-29 08:20
We were not able to reproduce this on our machines, but will try to dig more asap.

**Comment by hiddenpeanuts** [comment] 2023-03-29 13:54
I appreciate you looking into it. For what it's worth, I've seen the same error on two PCs.

**Comment by octimot** [comment] 2023-03-29 14:10
Sure! Thanks for the feedback!

Do you have any Python installed on your machine?
Also, would you mind running the .exe file with --skip-python-check at the end?

**Comment by octimot** [comment] 2023-03-29 15:12
I think we found the issue, and working on a fix. Will upload new installer for windows on the release page asap!

**Comment by octimot** [comment] 2023-03-29 17:33
This should have solved the issue: [StoryToolkitAI 0.17.16.1 for Windows](https://github.com/octimot/StoryToolkitAI/releases/download/v0.17.16/StoryToolkitAI.0.17.16.1.WIN.Installer.exe) (also available on the Release page)

Let me know if it works.

**Comment by octimot** [comment] 2023-03-29 18:21
No worries! It would be great if you test it out and see if it works when you can.

Cheers!

**Comment by octimot** [comment] 2023-03-30 05:23
Great!

**Closed by octimot** 2023-03-30 05:23 UTC
