### ISSUE TITLE
Install Errors

### ISSUE THREAD

**Issue by giodominice** [octimot/StoryToolkitAI#75] opened 2023-03-23 22:03 UTC
Hi!

I am unable to successfully use the software even though I followed the instructions exactly.  I am running a 13" M1 MacBook Pro 2020, 16GB memory, macOS 13.2.1 (22D68).

Please let me know if you need any further info!

These are the errors I received:

Here's the first one–
error: subprocess-exited-with-error
  
  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]

The second error–
 error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects

The third error–
ModuleNotFoundError: No module named 'torchaudio'

So yeah, not sure what to do at this point. Thanks in advance for your help!

Kind regards,
Giovanni
giodominice@gmail.com

**Comment by octimot** [comment] 2023-03-25 06:56
You may need to install rust for openai-whisper, check this how-to:
https://www.rust-lang.org/learn/get-started

Closing this issue since it's a duplicate of #74 
Feel free to re-open if this didn't help!

**Closed by octimot** 2023-03-25 06:56 UTC
