### ISSUE TITLE
"Split lines at....words" won't save.

### ISSUE THREAD

**Issue by Yoongbo** [octimot/StoryToolkitAI#141] opened 2023-11-14 05:14 UTC
I remember that in one of the earlier versions, I could set "Split lines at 1 words" and the SRT would be 1 word per line,. Now in v0.19.5, it reverts back to "characters" right after I click Save and stays as "characters" after I restart StoryToolkitAI, and even then, it won't have any effect. I've tried raising this number but the lines will always be split at the same hidden/default number of characters/words no matter what I specify there.

I also want to know if it's possible to generate a new SRT from the same transcription with new Transcription Post-Processing settings.  

StoryToolkitAI v0.19.5
Python 3.10.11
Windows 10
Connected to Resolve API (Resolve 18.6.2)

**Comment by octimot** [comment] 2024-01-10 09:06
Hey! 

Sorry for the late reply. 

Thanks for reporting! It wasn't really clear where this was happening and I couldn't reproduce it in the Ingest window initially.

But now I understood that you were referring to the fact that the words/characters value was not being saved in the Preferences window.

Anyways I found the issue and it will be fixed in the next update.

Cheers!

**Comment by octimot** [comment] 2024-01-16 19:35
I just pushed update 0.23.0 that should've resolved this, plus many others.

Cheers!

**Closed by octimot** 2024-01-16 19:35 UTC
Labels: bug
