### ISSUE TITLE
Subtitles stuck on repeat, hallucinations and possible solutions

### ISSUE THREAD

**Issue by x8086** [octimot/StoryToolkitAI#53] opened 2023-02-07 03:09 UTC
In I think at least 80% of the videos(2hrs long) I've tried to subtitle, after a certain random point in the video, the subs will repeat the same line forever until the end of the video. Sometimes it can happen as early as 20 mins, other times 1hr+ into it. Any guesses as to why or what can be done to fix it? I tried single channel audio, wave, mp3, still happens. It seems the spot where it gets stuck is the same spot for each sound file exported no matter how many times I run the transcription. If I export it again, it will be a different spot that gets stuck but it will get stuck. I've tried this 5 times on the same video with 5 different exports and it always gets stuck somewhere. 

I think this is a very important issue that turns this from a beautifully automated process into something that has to be manually inspected every time. It's often almost useless because it can't subtitle the whole movie. 

Also feature idea, often the dialogue would stop but the ai thinks they're still talking and will keep the last line on forever until the next recognizable dialogue happens. Add an automatic feature that will stop the repeat if a subtitle goes over 10 seconds. Obviously no subtitle line can last over 10 seconds. This is unrelated to the previous problem.

**Comment by octimot** [comment] 2023-02-08 07:34
> In I think at least 80% of the videos(2hrs long) I've tried to subtitle, after a certain random point in the video, the subs will repeat the same line forever until the end of the video. Sometimes it can happen as early as 20 mins, other times 1hr+ into it. Any guesses as to why or what can be done to fix it? I tried single channel audio, wave, mp3, still happens. It seems the spot where it gets stuck is the same spot for each sound file exported no matter how many times I run the transcription. If I export it again, it will be a different spot that gets stuck but it will get stuck. I've tried this 5 times on the same video with 5 different exports and it always gets stuck somewhere.

This is a known issue, most likely caused by hallucinations of AI. To manually retrigger the transcription process, select the lines that are wrong with "V" and hit "T" to re-transcribe only that portion: https://github.com/octimot/StoryToolkitAI#re-transcribing-transcripts

When re-transcribing, you can also try to use a different model to handle the more difficult parts of the audio, although most of the times that's not necessary.

> Also feature idea, often the dialogue would stop but the ai thinks they're still talking and will keep the last line on forever until the next recognizable dialogue happens. Add an automatic feature that will stop the repeat if a subtitle goes over 10 seconds. Obviously no subtitle line can last over 10 seconds. This is unrelated to the previous problem.

This is related to the hallucinations issue. Hard stopping and re-starting the AI at a given time interval is not ideal since it would make it lose the entire context of the audio, just as if you're feeding it new audio from that point on. In other words, the AI will consider the new chunk of audio a completely new audio file, but for some users this might be interesting. Will look into it, thanks!

**Comment by octimot** [comment] 2023-03-27 06:58
This has been greatly improved using the "Pre-detect speech" feature, so I will close the issue pending more feedback.

**Closed by octimot** 2023-03-27 06:58 UTC
Labels: enhancement
